Repository ksquareincmx/poc-chef-client, pull requests merged in 2019-03, with the labels that each got.

#34 item's modals removed
  package-lock.json
  package.json
  src/components/event/Create.tsx
  src/components/menuEvent/MenuContainer/MenuContainer.tsx
  src/partner/mappers/EventMapper.ts
  src/partner/models/Event.ts
  src/partner/modules/EventList/EventList.tsx
  src/partner/modules/EventList/EventListContainer.tsx
  src/partner/modules/EventList/EventListItem.tsx
  src/partner/modules/ui/Modal/index.js
  src/partner/modules/ui/index.ts
  src/partner/views/CurrentEventsView.tsx
  src/partner/views/EventView.tsx
Labels: enhancement

#38 validation in create component
  src/components/event/Create.tsx
  src/partner/services/EventService.ts
Labels: feature

#43 Enhancement/scroll to order list
  src/partner/modules/EventList/OrdersList.tsx
  src/partner/modules/ui/List/List.tsx
  src/partner/views/EventView.tsx
Labels: enhancement

#44 react and react-dom versions updated to 16.8.4
  package-lock.json
  package.json
Labels: enhancement

#45 hooks added to event view component
  src/partner/views/EventView.tsx
Labels: enhancement

#46 Enhancement/adopting hooks
  package-lock.json
  src/partner/modules/EventList/EventListItem.tsx
  src/partner/views/CurrentEventsView.tsx
  src/partner/views/PastEventsView.tsx
Labels: enhancement

#47 Enhancement/hooks into event orders component
  public/api/event_orders.json
  src/partner/modules/EventList/EventOrdersContainer.tsx
Labels: enhancement

#48 Enhancement/hooks into notification component
  src/components/event/Create.tsx
  src/providers/NotificationContext.tsx
Labels: enhancement

#51 hot-fix/using useRef hook instead of useState for DOM changes
  src/partner/modules/EventList/EventOrdersContainer.tsx
Labels: bug, enhancement

#52 floating button fixed
  src/components/FloatingAddButton/FloatingAddButton.tsx
Labels: enhancement

#53 user profile config added
  src/common/interfaces.tsx
  src/index.tsx
  src/partner/App.tsx
  src/user/App.tsx
  src/user/views/Profile/Profile.tsx
  src/user/views/Profile/index.js
Labels: feature

#57 user navbar added
  src/images/assignment-active.svg
  src/images/assignment.svg
  src/images/restaurant-active.svg
  src/images/restaurant.svg
  src/partner/modules/NavBar/NavBar.tsx
  src/user/App.tsx
  src/user/views/MyEvents/MyEvents.tsx
  src/user/views/MyEvents/index.tsx
  src/user/views/Order/Order.tsx
  src/user/views/Order/index.tsx
  src/user/views/Profile/Profile.tsx
Labels: feature

#58 stack events
  public/api/current_events.json
  src/partner/modules/ui/List/List.tsx
Labels: enhancement

#59 add-button color changed
  src/components/FloatingAddButton/FloatingAddButton.tsx
  src/images/add-button.svg
  src/partner/views/CurrentEventsView.tsx
Labels: enhancement

#60 order view added
  src/user/views/Order/Order.tsx
Labels: feature

#61 modal style fixed
  src/partner/modules/ui/List/List.tsx
  src/partner/modules/ui/Modal/Modal.tsx
  src/partner/views/CurrentEventsView.tsx
Labels: enhancement

#63 Feature/add users order view
  public/api/user_orders.json
  src/common/mappers/DateMapper.tsx
  src/common/ui/MenuOptions/MenuOptions.tsx
  src/common/ui/MenuOptions/index.tsx
  src/common/utils/utils.tsx
  src/partner/mappers/OrderMapper.ts
  src/partner/models/Order.tsx
  src/partner/modules/EventList/EventListItem.tsx
  src/partner/modules/NavBar/NavBar.tsx
  src/partner/modules/ui/List/List.tsx
  src/user/App.tsx
  src/user/modules/OrderList/OrderItem.tsx
  src/user/modules/OrderList/OrderListContainer.tsx
  src/user/modules/OrderList/OrderStyles.tsx
  src/user/modules/OrderList/ProductList.tsx
  src/user/modules/OrderList/index.tsx
  src/user/services/OrderService.tsx
  src/user/views/MyEvents/index.tsx
  src/user/views/MyOrders/MyOrders.tsx
  src/user/views/MyOrders/index.tsx
Labels: feature

#62 Feature/remove button added
  src/components/FloatingRemoveButton/FloatingRemoveButton.tsx
  src/images/remove-button.svg
  src/user/views/Order/Order.tsx
Labels: feature

#66 current event reducer added
  src/partner/App.tsx
  src/partner/ducks/currentEvent.ts
  src/partner/views/CurrentEventView.tsx
  src/partner/views/CurrentEventsView.tsx
  src/partner/views/index.ts
Labels: enhancement

#69 past event reducer added
  src/partner/ducks/pastEvent.ts
  src/partner/views/PastEventsView.tsx
Labels: enhancement
