Repository ksquareincmx/poc-chef-client, pull requests merged in 2019-05, with the labels that each got.

#132 Implement api on event details
  src/partner/App.tsx
  src/partner/modules/CardEvent/CardEvent.tsx
  src/partner/modules/CardOrder/OptionsCardOrder.tsx
  src/partner/routes/index.ts
  src/partner/routes/routes.ts
  src/partner/services/EventService.ts
  src/partner/views/EventDetails/EventDetails.tsx
  src/partner/views/EventDetails/EventDetailsContainer.tsx
Labels: feature

#135 Add user events view
  src/common/mappers/index.ts
  src/common/views/EmptyData/EmptyData.tsx
  src/images/pork_sad.svg
  src/user/App.tsx
  src/user/mappers/OrderMapper.ts
  src/user/mappers/OrderProductMapper.ts
  src/user/mappers/UserEventMapper.ts
  src/user/mappers/index.ts
  src/user/models/Order.ts
  src/user/models/OrderProduct.ts
  src/user/models/UserEvent.ts
  src/user/modules/EmptyEvents/EmptyEvents.tsx
  src/user/modules/EmptyEvents/index.ts
  src/user/modules/EventCard/EventCard.tsx
  src/user/modules/EventCard/index.ts
  src/user/modules/EventsContainer/EventList.tsx
  src/user/modules/EventsContainer/EventsContainer.tsx
  src/user/modules/EventsContainer/index.ts
  src/user/modules/ProductsEditListContainer/ProductEditRow.tsx
  src/user/modules/ProductsEditListContainer/ProductsListContainer.tsx
  src/user/modules/ui/ProductEditRow/ProductEditRow.ts
  src/user/modules/ui/ProductEditRow/index.ts
  src/user/services/UserEventService.ts
  src/user/views/Events/Events.tsx
  src/user/views/Events/index.ts
  src/user/views/OrderEdit/OrderEditContainer.tsx
Labels: feature

#136 implement api to create new order
  src/user/ducks/order.ts
  src/user/mappers/OrderMapper.ts
  src/user/mappers/UserEventMapper.ts
  src/user/models/Order.ts
  src/user/models/UserEvent.ts
  src/user/modules/EventCard/EventCard.tsx
  src/user/modules/ProductsEditListContainer/ProductEditRow.tsx
  src/user/modules/ProductsEditListContainer/ProductsListContainer.tsx
  src/user/services/OrderService.tsx
Labels: feature

#127 Add edit profile view
  src/images/icons/assignment-active.svg
  src/images/icons/assignment.svg
  src/images/icons/close.svg
  src/images/icons/history-active.svg
  src/images/icons/history.svg
  src/images/icons/mail.svg
  src/images/icons/phone.svg
  src/images/icons/restaurant-menu-active.svg
  src/images/icons/restaurant-menu.svg
  src/images/icons/user.svg
  src/images/profile.png
  src/images/user-logo.svg
  src/partner/modules/Header/Header.tsx
  src/partner/modules/ui/Header/Header.tsx
  src/user/App.tsx
  src/user/modules/EditProfileCard/EditProfileCard.tsx
  src/user/modules/EditProfileCard/index.ts
  src/user/modules/Navbar/Navbar.tsx
  src/user/modules/ProfileCard/ProfileCard.tsx
  src/user/modules/ProfileCard/index.ts
  src/user/modules/ui/EditProfileCard/EditProfileCard.tsx
  src/user/modules/ui/EditProfileCard/index.ts
  src/user/modules/ui/Profile/index.ts
  src/user/modules/ui/ProfileCard/Profile.ts
  src/user/modules/ui/ProfileCard/index.ts
  src/user/routes/index.ts
  src/user/routes/routes.ts
  src/user/views/EditProfile/EditProfile.tsx
  src/user/views/EditProfile/index.ts
  src/user/views/Profile/Profile.tsx
  src/user/views/Profile/index.js
Labels: enhancement

#141 Hotfix: use correct component in router
  src/user/App.tsx
  src/user/views/EditProfile/EditProfile.tsx
Labels: bug

#142 Format dates with moment
  src/common/mappers/DateMapper.tsx
  src/partner/mappers/OrderMapper.ts
  src/partner/models/Order.tsx
  src/user/modules/OrderList/OrderItem.tsx
Labels: enhancement

#148 Add hardcoded products ids
  src/common/mappers/DateMapper.tsx
  src/partner/mappers/EventMapper.ts
  src/partner/mappers/ProductsMapper.ts
  src/partner/views/CreateEvent/CreateEvent.tsx
  src/user/modules/EventCard/EventCard.tsx
Labels: enhancement

#150 Show event orders in event details, mark order as paid/unpaid
  src/partner/ducks/eventOrders.test.ts
  src/partner/ducks/eventOrders.ts
  src/partner/mappers/EventMapper.ts
  src/partner/mappers/OrderMapper.ts
  src/partner/models/Order.tsx
  src/partner/modules/CardOrder/CardOrder.tsx
  src/partner/modules/CardOrder/OptionsCardOrder.tsx
  src/partner/modules/CardOrder/ProductsOrderContainer.tsx
  src/partner/modules/EventList/EventOrdersContainer.tsx
  src/partner/services/EventService.ts
  src/partner/services/OrderService.ts
  src/partner/views/EventDetails/EventDetailsContainer.tsx
  src/partner/views/EventDetails/OrderListContainer.tsx
Labels: feature

#151 Implement api to update an order
  src/user/mappers/OrderMapper.ts
  src/user/mappers/UserEventMapper.ts
  src/user/models/Order.ts
  src/user/modules/OrderList/OrderItem.tsx
  src/user/modules/OrderList/ProductList.tsx
  src/user/services/OrderService.tsx
  src/user/views/OrderEdit/OrderEditContainer.tsx
Labels: feature

#158 Format prices
  src/common/utils/index.ts
  src/common/utils/utils.ts
  src/partner/mappers/OrderMapper.ts
  src/partner/models/Order.tsx
  src/partner/modules/CardEvent/CardEvent.tsx
  src/partner/modules/CardOrder/CardOrder.tsx
  src/partner/modules/CardOrder/ProductsOrderContainer.tsx
  src/user/modules/OrderList/OrderItem.tsx
  src/user/modules/OrderList/ProductList.tsx
  src/user/modules/ProductsEditListContainer/ProductEditRow.tsx
  src/user/views/OrderEdit/OrderEditContainer.tsx
Labels: enhancement

#157 Get jwt after login
  src/common/services/LoginService.ts
  src/partner/services/EventService.ts
  src/partner/services/OrderService.ts
  src/user/services/OrderService.tsx
  src/user/services/UserEventService.ts
Labels: bug

#156 Style changes
  src/images/restaurant-menu-active.svg
  src/partner/App.tsx
  src/partner/modules/NavBar/NavBar.tsx
  src/user/mappers/OrderProductMapper.ts
  src/user/mappers/UserEventMapper.ts
  src/user/modules/EventCard/EventCard.tsx
  src/user/modules/Navbar/Navbar.tsx
Labels: enhancement

#159 fix logic to mark a tab as active
  src/partner/modules/NavBar/NavBar.tsx
Labels: bug

#163 fix styles on chrome
  src/partner/modules/InputDatePicker/InputDatePicker.tsx
  src/partner/views/CreateEvent/CreateEventContainer.tsx
Labels: bug

#164 Divs flexibles
  src/common/consts/index.ts
  src/common/consts/styles.ts
  src/common/ui/Card/Card.ts
  src/common/ui/ContentWrapper/ContentWrapper.ts
  src/common/ui/MainDivContainer/MainDivContainer.ts
  src/index.tsx
  src/partner/App.tsx
  src/partner/modules/InputDatePicker/InputDatePicker.tsx
  src/partner/modules/InputLabel/InputLabel.tsx
  src/partner/modules/ui/Header/Header.tsx
  src/partner/modules/ui/LabelInput/LabelInput.ts
  src/partner/modules/ui/List/List.tsx
  src/partner/modules/ui/Modal/Notification.tsx
  src/partner/modules/ui/NavBar/NavBar.ts
  src/partner/views/CreateEvent/CreateEventContainer.tsx
  src/partner/views/CreateEvent/ProductRow.tsx
  src/partner/views/CurrentEvents/CurrentEvents.tsx
  src/partner/views/CurrentEvents/CurrentEventsContainer.tsx
  src/user/modules/ui/NavBar/NavBar.ts
Labels: enhancement

#166 Protect routes
  src/common/mappers/LoginMapper.ts
  src/common/services/LoginService.ts
  src/partner/App.tsx
  src/partner/views/Login/Login.tsx
  src/partner/views/Login/LoginEmailForm.tsx
  src/user/App.tsx
  src/user/views/Login/Login.tsx
Labels: enhancement

#162 add cancel event, redirect to current events view after cancel it
  src/common/interfaces.tsx
  src/partner/services/EventService.ts
  src/partner/views/CreateEvent/CreateEvent.tsx
  src/partner/views/CreateEvent/CreateEventContainer.tsx
  src/user/modules/EventCard/EventCard.tsx
  src/user/modules/OrderList/OrderItem.tsx
Labels: feature

#168 change regex to validate a protected route
  src/partner/App.tsx
  src/user/App.tsx
Labels: bug

#171 add a dockerfile and a nginx confing
  Dockerfile
  nginx.conf
Labels: feature

#172 verify user role in login
  src/common/services/LoginService.ts
  src/partner/views/Login/Login.tsx
  src/user/App.tsx
  src/user/views/Login/Login.tsx
Labels: bug

#173 add error handler to current and past events in partner app
  src/partner/services/EventService.ts
  src/partner/views/CurrentEvents/CurrentEvents.tsx
  src/partner/views/PastEvents/PastEvents.tsx
Labels: enhancement

#174 Remove unused code partner and user app
  src/partner/ducks/currentEvent.ts
  src/partner/ducks/currentEvents.test.ts
  src/partner/ducks/event.ts
  src/partner/ducks/events.test.ts
  src/partner/ducks/pastEvent.ts
  src/partner/ducks/pastEvents.test.ts
  src/partner/modules/EventList/EventList.tsx
  src/partner/modules/ui/List/List.ts
  src/partner/modules/ui/List/List.tsx
  src/partner/modules/ui/Modal/Modal.tsx
  src/partner/modules/ui/Modal/index.js
  src/partner/modules/ui/Notification/Notification.tsx
  src/partner/modules/ui/Notification/index.ts
  src/partner/modules/ui/index.ts
  src/providers/NotificationContext.tsx
  src/user/ducks/myOders.test.ts
  src/user/ducks/myOrders.ts
  src/user/ducks/order.ts
  src/user/modules/OrderList/OrderListContainer.tsx
Labels: enhancement

#175 Update event model
  src/partner/mappers/EventMapper.ts
  src/partner/models/Event.ts
  src/partner/services/EventService.ts
  src/user/mappers/UserEventMapper.ts
Labels: feature
